#!/bin/sh
#
# Do rough backup of uploads and database.

set -e

cd "$(dirname "$0")"
# Requires that you define an expiry-dates-backup item in your rclone configuration.
rclone copy upload expiry-dates-backup:expiry-dates/upload
rclone copy db.sqlite3 expiry-dates-backup:expiry-dates/$(date --iso-8601=seconds)/db.sqlite3
