# Generated by Django 5.1.4 on 2025-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varenavn_text', models.CharField(max_length=200)),
                ('udløb_date', models.DateTimeField(verbose_name='udløbsdato')),
            ],
        ),
    ]
