# Generated by Django 5.1.4 on 2025-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vare',
            name='udløb_date',
            field=models.DateField(verbose_name='udløbsdato'),
        ),
        migrations.AlterField(
            model_name='vare',
            name='varenavn_text',
            field=models.CharField(max_length=200, verbose_name='varenavn'),
        ),
    ]
