# Generated by Django 5.1.4 on 2025-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varer', '0002_alter_vare_udløb_date_alter_vare_varenavn_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vare',
            options={'verbose_name_plural': 'varer'},
        ),
        migrations.AddField(
            model_name='vare',
            name='vare_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='billede'),
        ),
    ]
