# Generated by Django 5.1.4 on 2025-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varer', '0003_alter_vare_options_vare_vare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vare',
            name='udløb_date',
            field=models.DateField(blank=True, verbose_name='udløbsdato'),
        ),
        migrations.AlterField(
            model_name='vare',
            name='vare_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='billede'),
        ),
    ]
