# Generated by Django 5.1.4 on 2025-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varer', '0004_alter_vare_udløb_date_alter_vare_vare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vare',
            name='udløb_date',
            field=models.DateField(blank=True, null=True, verbose_name='udløbsdato'),
        ),
    ]
