# Generated by Django 5.1.4 on 2025-01-14 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varer', '0005_alter_vare_udløb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varegruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varegruppe_text', models.CharField(max_length=200, verbose_name='gruppenavn')),
            ],
        ),
        migrations.AddField(
            model_name='vare',
            name='varegruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varer.varegruppe'),
        ),
    ]
